server:
  port: 9203
#spring:
#  redis:
#    host: localhost
#    password: '@Import_Express.Auth_123'
#    port: 6379
#  cloud:
#    gateway:
#      routes:
#        - id: requestratelimiter_route
#          uri: http://localhost:8201
#          filters:
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 1 #每秒允许处理的请求数量
#                redis-rate-limiter.burstCapacity: 2 #每秒最大处理的请求数量
#                key-resolver: "#{@ipKeyResolver}" #限流策略，对应策略的Bean
#          predicates:
#            - Method=GET
#对指定数量的路径前缀进行去除的过滤器。
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: strip_prefix_route
#          uri: http://localhost:8201
#          predicates:
#            - Path=/user-service/**
#          filters:
#            - StripPrefix=2
  #ghj与StripPrefix过滤器恰好相反，会对原有路径进行增加操作的过滤器。
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: prefix_path_route
#          uri: http://localhost:8201
#          predicates:
#            - Method=GET
#          filters:
#            - PrefixPath=/user

#对路由请求进行重试的过滤器，可以根据路由请求返回的HTTP状态码来确定是否进行重试。
spring:
  cloud:
    gateway:
      routes:
        - id: retry_route
          uri: http://localhost:8201
          predicates:
            - Method=GET
          filters:
            - name: Retry
              args:
                retries: 1 #需要进行重试的次数
                statuses: BAD_GATEWAY #返回哪个状态码需要进行重试，返回状态码为5XX进行重试
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false





logging:
  level:
    org.springframework.cloud.gateway: debug
