server:
  port: 9202
service-url:
  user-service: http://localhost:8201
spring:
  cloud:
    gateway:
      routes:
#        - id: remoteaddr_route
#          uri: ${service-url.user-service}
#          predicates:
            # 在指定时间之后的请求会匹配该路由。- id: after_route
            # - After=2021-01-25T11:55:00+08:00[Asia/Shanghai]
            # 在指定时间之前的请求会匹配该路由。  - id: before_route
            # - Before=2019-09-24T16:30:00+08:00[Asia/Shanghai]
            # 在指定时间区间内的请求会匹配该路由。 - id: before_route
            # - Between=2019-09-24T16:30:00+08:00[Asia/Shanghai], 2019-09-25T16:30:00+08:00[Asia/Shanghai]
            # 带有指定Cookie的请求会匹配该路由。 - id: cookie_route
            #  - Cookie=username,macro
            # 带有指定请求头的请求会匹配该路由。- id: header_route
            # - Header=X-Request-Id, \d+
            # 带有指定Host的请求会匹配该路由。 - id: host_route
            # - Host=**.macrozheng.com
            # 发送指定方法的请求会匹配该路由。 - id: method_route
            # - Method=GET
            # 发送指定路径的请求会匹配该路由。 - id: path_route
            # - Path=/user/{id}
            # 带指定查询参数的请求可以匹配该路由。- id: query_route
            #  - Query=username
            #  从指定远程地址发起的请求可以匹配该路由。 - id: remoteaddr_route
            # - RemoteAddr=192.168.1.1/24
            # 使用权重来路由相应请求，以下表示有80%的请求会被路由到localhost:8201，20%会被路由到localhost:8202。
          - id: weight_high
            uri: http://localhost:8201
            predicates:
                - Weight=group1, 8
          - id: weight_low
            uri: http://localhost:8202
            predicates:
              - Weight=group1, 2
