server:
  port: 8701
spring:
  application:
    name: feign-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
feign:
  hystrix:
    enabled: true #在Feign中开启Hystrix
  compression:
    request:
      enabled: false #是否对请求进行GZIP 压缩
      min-request-size: 2048 #超过该大小的请求会被压缩
      mime-types: text/xml,application/xml,application/json #指定压缩的请求数据类型
    response:
      enabled: false #是否对相应进行GZIP压缩
logging:
  level: #修改日志级别
    com.lip.training.service.UserService: debug
ribbon:
  ConnectTimeout: 1000 #服务请求连接超时时间（毫秒）
  ReadTimeout: 3000 #服务请求处理超时时间（毫秒）
  OkToRetryOnAllOperations: true #对超时请求启用重试机制
  MaxAutoRetriesNextServer: 1 #切换重试实例的最大个数
  MaxAutoRetries: 1 # 切换实例后重试最大次数
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #修改负载均衡算法

#user-service:
#  ribbon:
#    ConnectTimeout: 1000 #服务请求连接超时时间（毫秒）
#    ReadTimeout: 3000 #服务请求处理超时时间（毫秒）
#    OkToRetryOnAllOperations: true #对超时请求启用重试机制
#    MaxAutoRetriesNextServer: 1 #切换重试实例的最大个数
#    MaxAutoRetries: 1 # 切换实例后重试最大次数
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #修改负载均衡算法